import React from 'react';
import { 
  ShieldCheck, 
  FileCheck2, 
  Binary, 
  Building2, 
  ExternalLink,
  ArrowRight,
  Sparkles
} from 'lucide-react';
import { Link } from '../../lib/router';

export const TrustSourcesSection: React.FC = () => {
  return (
    <section id="trust-sources" className="py-20 lg:py-28 bg-[#0b1813] relative overflow-hidden border-b border-[#c8a45d]/20">
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full text-xs font-mono uppercase tracking-widest text-[#dfbe7b] bg-[#142e25]/60 border border-[#c8a45d]/30 mb-4">
            Defensibility & Provenance
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-[#f5f1e7] font-serif-heading tracking-tight">
            Trust & Source Traceability
          </h2>
          <p className="mt-4 text-base sm:text-lg text-[#d6ccb6] font-light">
            In regulatory affairs, an answer without provenance is a liability. Every conclusion generated by IP-SAKTI Sahayak follows an unbroken statutory chain of custody.
          </p>
        </div>

        {/* The Visual Lineage Diagram: Claim -> Evidence -> Document Version -> Official Source */}
        <div className="bg-[#08130f] border border-[#c8a45d]/30 rounded-3xl p-6 sm:p-10 shadow-2xl relative">
          
          <div className="mb-6 flex flex-wrap items-center justify-between gap-4 pb-6 border-b border-[#1c3e32]">
            <div>
              <span className="text-xs uppercase tracking-widest text-[#c8a45d] font-mono font-semibold">
                Live Audit Chain Demo
              </span>
              <h3 className="text-xl font-bold text-[#f5f1e7] font-serif-heading">
                Verifiable Evidentiary Lineage Architecture
              </h3>
            </div>
            <div className="flex items-center space-x-2 px-3 py-1 rounded-full bg-[#142e25] border border-[#14b8a6]/40 text-[#2dd4bf] text-xs font-mono">
              <span className="w-2 h-2 rounded-full bg-[#14b8a6] animate-pulse" />
              <span>Cryptographic Integrity Verified</span>
            </div>
          </div>

          {/* 4-Step Chain */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 relative">
            
            {/* Step 1: Claim */}
            <div className="bg-[#0f221b] border border-[#c8a45d]/25 rounded-2xl p-5 flex flex-col justify-between relative group hover:border-[#c8a45d] transition-all">
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-[11px] font-mono px-2 py-0.5 rounded bg-[#08130f] text-[#dfbe7b] border border-[#c8a45d]/30">
                    STAGE 1
                  </span>
                  <Sparkles className="w-4 h-4 text-[#dfbe7b]" />
                </div>
                <div className="text-xs uppercase font-mono tracking-wider text-[#c8a45d] mb-1">
                  Synthesized Claim
                </div>
                <p className="text-sm font-semibold text-[#f5f1e7] leading-snug">
                  "Applicable Section 3(p) statutory patentability bar excludes raw herb aggregation."
                </p>
              </div>
              <div className="mt-4 pt-3 border-t border-[#1c3e32] text-[11px] text-[#d6ccb6]/70 font-mono">
                Status: Statutorily Barred
              </div>
              <div className="hidden md:block absolute -right-3 top-1/2 -translate-y-1/2 z-10">
                <ArrowRight className="w-5 h-5 text-[#c8a45d]" />
              </div>
            </div>

            {/* Step 2: Evidence */}
            <div className="bg-[#0f221b] border border-[#c8a45d]/25 rounded-2xl p-5 flex flex-col justify-between relative group hover:border-[#c8a45d] transition-all">
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-[11px] font-mono px-2 py-0.5 rounded bg-[#08130f] text-[#2dd4bf] border border-[#14b8a6]/30">
                    STAGE 2
                  </span>
                  <FileCheck2 className="w-4 h-4 text-[#2dd4bf]" />
                </div>
                <div className="text-xs uppercase font-mono tracking-wider text-[#14b8a6] mb-1">
                  Evidentiary Excerpt
                </div>
                <p className="text-xs text-[#d6ccb6] leading-relaxed">
                  Chapter IV Para 10.12: "Specification must provide quantitative comparative synergy data to overcome Section 3(e)."
                </p>
              </div>
              <div className="mt-4 pt-3 border-t border-[#1c3e32] text-[11px] text-[#2dd4bf] font-mono">
                Ref: EVID-IPO-PHARMA
              </div>
              <div className="hidden md:block absolute -right-3 top-1/2 -translate-y-1/2 z-10">
                <ArrowRight className="w-5 h-5 text-[#c8a45d]" />
              </div>
            </div>

            {/* Step 3: Document Version */}
            <div className="bg-[#0f221b] border border-[#c8a45d]/25 rounded-2xl p-5 flex flex-col justify-between relative group hover:border-[#c8a45d] transition-all">
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-[11px] font-mono px-2 py-0.5 rounded bg-[#08130f] text-[#dfbe7b] border border-[#c8a45d]/30">
                    STAGE 3
                  </span>
                  <Binary className="w-4 h-4 text-[#dfbe7b]" />
                </div>
                <div className="text-xs uppercase font-mono tracking-wider text-[#c8a45d] mb-1">
                  Document Version
                </div>
                <p className="text-xs text-[#eae3d2] leading-snug font-medium">
                  The Patents Act, 1970 (Act 39 of 1970) as amended by Act 15 of 2005.
                </p>
                <div className="mt-2 text-[10px] text-[#d6ccb6]/60 font-mono break-all">
                  SHA256: 4f8e02a...10a4
                </div>
              </div>
              <div className="mt-4 pt-3 border-t border-[#1c3e32] text-[11px] text-[#dfbe7b] font-mono">
                Gazette Part II Sec 1
              </div>
              <div className="hidden md:block absolute -right-3 top-1/2 -translate-y-1/2 z-10">
                <ArrowRight className="w-5 h-5 text-[#c8a45d]" />
              </div>
            </div>

            {/* Step 4: Official Source */}
            <div className="bg-[#0f221b] border border-[#c8a45d]/25 rounded-2xl p-5 flex flex-col justify-between group hover:border-[#c8a45d] transition-all">
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-[11px] font-mono px-2 py-0.5 rounded bg-[#08130f] text-[#14b8a6] border border-[#14b8a6]/30">
                    STAGE 4
                  </span>
                  <Building2 className="w-4 h-4 text-[#2dd4bf]" />
                </div>
                <div className="text-xs uppercase font-mono tracking-wider text-[#14b8a6] mb-1">
                  Official Authority
                </div>
                <p className="text-xs text-[#eae3d2] leading-snug font-medium">
                  Office of the Controller General of Patents, Designs & Trademarks (CGPDTM).
                </p>
                <a
                  href="https://ipindia.gov.in"
                  target="_blank"
                  rel="noreferrer"
                  className="mt-2 inline-flex items-center space-x-1 text-[11px] text-[#dfbe7b] hover:underline"
                >
                  <span>ipindia.gov.in</span>
                  <ExternalLink className="w-3 h-3" />
                </a>
              </div>
              <div className="mt-4 pt-3 border-t border-[#1c3e32] text-[11px] text-[#14b8a6] font-mono">
                Verified Authority Portal
              </div>
            </div>

          </div>

          {/* Bottom explanation */}
          <div className="mt-8 p-4 rounded-xl bg-[#0b1813] border border-[#c8a45d]/20 text-xs text-[#d6ccb6] flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center space-x-3">
              <ShieldCheck className="w-5 h-5 text-[#dfbe7b] shrink-0" />
              <span>
                Zero hallucinations. If a statutory proposition cannot be mapped to an official gazette or court precedent, it is rejected by the synthesis filter.
              </span>
            </div>
            <Link
              href="/ask"
              className="shrink-0 text-xs font-semibold text-[#dfbe7b] hover:text-[#f5f1e7] flex items-center space-x-1"
            >
              <span>Test with your formulation</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>

        </div>

      </div>
    </section>
  );
};
